# Generated by Django 3.0.6 on 2020-05-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_enderecos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='desricao',
            new_name='descricao',
        ),
    ]
